vcom -work work -2008 -explicit src/self_test.vhd
vcom -work work -2008 -explicit src/tb_selftest.vhd
vcom -work work -2008 -explicit src/pulse_width_modulator.vhd
vcom -work work -2008 -explicit src/pwm.vhd
vcom -work work -2008 -explicit src/tb_pwm.vhd
vcom -work work -2008 -explicit src/tb_pwm_module.vhd
vcom -work work -2008 -explicit src/output_synchronizer.vhd
vcom -work work -2008 -explicit src/input_synchronizer.vhd
vcom -work work -2008 -explicit src/tb_output_synchronizer.vhd
vcom -work work -2008 -explicit src/quadrature_decoder.vhd
vcom -work work -2008 -explicit src/tb_quadrature_decoder.vhd
vcom -work work -2008 -explicit src/velocity_reader.vhd
vcom -work work -2008 -explicit src/tb_velocity_system.vhd
vcom -work work -2008 -explicit src/seg7ctrl/bin2ssd_pck.vhd
vcom -work work -2008 -explicit src/seg7ctrl/bin2ssd.vhd
vcom -work work -2008 -explicit src/seg7ctrl/seg7ctrl_ent.vhd
vcom -work work -2008 -explicit src/seg7ctrl/seg7ctrl.vhd
vcom -work work -2008 -explicit src/system.vhd
vcom -work work -2008 -explicit src/tb_motor_system.vhd
